name: chat_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  blur: ^3.1.0
  smooth_page_indicator: ^1.1.0
  get_it: ^7.6.7
  image_picker: ^1.0.4
  community_material_icon: ^5.8.55
  flutter_bloc: ^8.1.1  
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  provider: ^6.0.5
  flutter_launcher_icons: ^0.13.1
  animated_text_kit: ^4.2.2
  hive_flutter: ^1.1.0
  story_viewer: ^0.2.0
  hive: ^2.2.3
  google_nav_bar: ^5.0.6
  animations: ^2.0.7
  modal_bottom_sheet: ^2.1.2
  pinput: ^3.0.1
  mask_text_input_formatter: ^2.4.0
  get: ^4.6.5
  flutter_spinkit: ^5.1.0
  sizer: ^2.0.15
  sidebarx: ^0.16.2
  lite_rolling_switch: ^1.0.1
  liquid_pull_to_refresh: ^3.0.1
  #firebase [services]
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_database: ^10.4.0
  firebase_storage: ^11.6.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
