// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFqQu-reR1o_uLFhSSDuUBJjQrAoj55ac',
    appId: '1:449563345912:web:c4be3703a2e9fdfad14c0d',
    messagingSenderId: '449563345912',
    projectId: 'chat-3e88f',
    authDomain: 'chat-3e88f.firebaseapp.com',
    storageBucket: 'chat-3e88f.appspot.com',
    measurementId: 'G-RW5XFY2PC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV_5tY5nSvnyPQy_5hCC4UNBTpEhTgp28',
    appId: '1:449563345912:android:d4707d861beda109d14c0d',
    messagingSenderId: '449563345912',
    projectId: 'chat-3e88f',
    storageBucket: 'chat-3e88f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdxKscZu2FzdFikTamrf53M4PYL8HofVQ',
    appId: '1:449563345912:ios:b162990768658f06d14c0d',
    messagingSenderId: '449563345912',
    projectId: 'chat-3e88f',
    storageBucket: 'chat-3e88f.appspot.com',
    androidClientId: '449563345912-pkr9anrp9kjqrps1fnf7d488296adrgp.apps.googleusercontent.com',
    iosClientId: '449563345912-4nah7200hq7rccujafcjgimspfg57k48.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdxKscZu2FzdFikTamrf53M4PYL8HofVQ',
    appId: '1:449563345912:ios:b162990768658f06d14c0d',
    messagingSenderId: '449563345912',
    projectId: 'chat-3e88f',
    storageBucket: 'chat-3e88f.appspot.com',
    androidClientId: '449563345912-pkr9anrp9kjqrps1fnf7d488296adrgp.apps.googleusercontent.com',
    iosClientId: '449563345912-4nah7200hq7rccujafcjgimspfg57k48.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
